### ISSUE TITLE
支付宝异步通知【签名验证失败】

### ISSUE THREAD

**Issue by liuwave** [yunwuxin/think-pay#2]
支付宝异步通知【签名验证失败】，能够正常支付，主动查询支付结果的验签也能通过，就是异步通知的验签出错，调试了很久不知道是什么原因。

异步通知验签异常：`[2020-06-04T22:55:41+08:00][error] [0]签名验证失败[/www/wwwroot/***/vendor/yunwuxin/think-pay/src/channel/Alipay.php:121]`

异步通知的数据比较敏感，不好贴出来，有人遇到过吗？ 要从哪些方面下手？

**Comment by liuwave** [comment]
用的默认的NotifyController控制器，路由也未作更改。

**Comment by yunwuxin** [comment]
你用的哪个版本

**Comment by liuwave** [comment]
使用的是这个：
 "topthink/framework": "^6.0.0",   
 "yunwuxin/think-pay": "^3.0",

**Comment by yunwuxin** [comment]
这个版本我们一直在用  没发现问题   检查下你们的配置是否正确

**Comment by liuwave** [comment]
找到原因了，是因为设置了全局变量过滤 `protected $filter = ['trim', 'htmlspecialchars'];`，把这个去掉就OK了。

**Comment by liuwave** [comment]
建议获取变量这块改成 `$data = $request->post('',null,null);`

**Comment by yunwuxin** [comment]
可以直接pr
